# @host = https://localhost
@host = https://localhost
@port = 7127

@LibraryCRM.API_HostAddress = https://localhost:7127

GET {{LibraryCRM.API_HostAddress}}/api/book/8c64b4e1-1a35-4cf0-b6cf-f37c0b0a0db4

###
